<template>
  <CLightMode>
    <CStack
      direction="row"
      align-self="center"
      justify="center"
      font-size="xl"
      my="2"
    >
      <CButton
        to="/"
        left-icon="home"
        variant-color="indigo"
        as="nuxt-link"
        font-size="lg"
        box-shadow="md"
        px="3"
      />
      <CButton
        as="a"
        href="https://github.com/thunderjr"
        target="_blank"
        left-icon="github"
        variant="outline"
        variant-color="indigo"
        font-size="lg"
        box-shadow="md"
        px="3"
        bg="#fff"
      />
      <CButton
        as="a"
        href="https://www.linkedin.com/in/flávio-marques-07b566194/"
        target="_blank"
        left-icon="linkedin"
        variant="outline"
        variant-color="indigo"
        font-size="lg"
        box-shadow="md"
        px="3"
        bg="#fff"
      />
    </CStack>
  </CLightMode>
</template>
